@startuml

entity "Recette" {
  + id: int <<PK>>
  + titre: string
  + preparation: string
}

entity "Recette_Ingrédient" {
  + recette_id: int <<PK>> <<FK>>
  + ingredient_id: int <<PK>> <<FK>>
  + quantite: string
  + unite: string
}

entity "Ingrédient" {
  + id: int <<PK>>
  + nom: string
}

entity "Catégorie" {
  + id: int <<PK>>
  + nom: string
}

entity "Relation_Ingredient_Categorie" {
  + id: int <<PK>>
  + ingredient_id: int <<FK>>
  + categorie_id: int <<FK>>
  + type_relation: string <<ENUM>>  // 'super' ou 'sous'
}

Recette "1,1" -- "0,n" Recette_Ingrédient : contient
Recette_Ingrédient "1,1" -- "1,1" Ingrédient : référence
Ingrédient "0,n" -- "0,n" Relation_Ingredient_Categorie : a une relation avec
Catégorie "0,n" -- "0,n" Relation_Ingredient_Categorie : est liée à

@enduml
